# frozen_string_literal: true

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create(username: 'Tomaszowy', email: 'admin@example.com', password: '123456')

Skill.create(name: 'Siła', start_value: 8, parent_stat: Skill::STAT_NAMES[0], is_equal_to_stat: true)
Skill.create(name: 'Pływanie', start_value: 8, parent_stat: Skill::STAT_NAMES[0])
Skill.create(name: 'Ciężarowiec', start_value: 4, parent_stat: Skill::STAT_NAMES[0])

Skill.create(name: 'Odporność na ból', start_value: 8, parent_stat: Skill::STAT_NAMES[1], is_equal_to_stat: true)
Skill.create(name: 'Instynkt walki', start_value: 4, parent_stat: Skill::STAT_NAMES[1])
Skill.create(name: 'Medytacja', start_value: 4, parent_stat: Skill::STAT_NAMES[1])

Skill.create(name: 'Czytanie i pisanie', start_value: 8, parent_stat: Skill::STAT_NAMES[2])
Skill.create(name: 'Język ojczysty', start_value: 8, parent_stat: Skill::STAT_NAMES[2], is_equal_to_stat: true)
Skill.create(name: 'Przebieranie się', start_value: 8, parent_stat: Skill::STAT_NAMES[2])
Skill.create(name: 'Używanie elektroniki', start_value: 8, parent_stat: Skill::STAT_NAMES[2])
Skill.create(name: 'Używanie komputera', start_value: 8, parent_stat: Skill::STAT_NAMES[2])
Skill.create(name: 'Analiza danych', start_value: 4, parent_stat: Skill::STAT_NAMES[2])
Skill.create(name: 'Bioinżynieria', start_value: 4, parent_stat: Skill::STAT_NAMES[2])
Skill.create(name: 'Biologia', start_value: 4, parent_stat: Skill::STAT_NAMES[2])
Skill.create(name: 'Chemia', start_value: 4, parent_stat: Skill::STAT_NAMES[2])
Skill.create(name: 'Fizyka', start_value: 4, parent_stat: Skill::STAT_NAMES[2])
Skill.create(name: 'Informatyka', start_value: 4, parent_stat: Skill::STAT_NAMES[2])
Skill.create(name: 'Inżynieria budowlana', start_value: 4, parent_stat: Skill::STAT_NAMES[2])
Skill.create(name: 'Inżynieria elektryczna', start_value: 4, parent_stat: Skill::STAT_NAMES[2])
Skill.create(name: 'Inżynieria mechaniczna', start_value: 4, parent_stat: Skill::STAT_NAMES[2])
Skill.create(name: 'Inżynieria mikrotroniczna', start_value: 4, parent_stat: Skill::STAT_NAMES[2])
Skill.create(name: 'Inżynieria nukleoniczna', start_value: 4, parent_stat: Skill::STAT_NAMES[2])
Skill.create(name: 'Matematyka', start_value: 4, parent_stat: Skill::STAT_NAMES[2])
Skill.create(name: 'Medycyna', start_value: 4, parent_stat: Skill::STAT_NAMES[2])
Skill.create(name: 'Nanoinżynieria', start_value: 4, parent_stat: Skill::STAT_NAMES[2])
Skill.create(name: 'Sport: [dyscyplina]', start_value: 4, parent_stat: Skill::STAT_NAMES[2])
Skill.create(name: 'Teorie spiskowe', start_value: 4, parent_stat: Skill::STAT_NAMES[2])
Skill.create(name: 'Techniki pamięciowe', start_value: 0, parent_stat: Skill::STAT_NAMES[2])
Skill.create(name: 'Sieciarstwo', start_value: 0, parent_stat: Skill::STAT_NAMES[2])

Skill.create(name: 'Gry komputerowe', start_value: 8, parent_stat: Skill::STAT_NAMES[3])
Skill.create(name: 'Komunikacja', start_value: 8, parent_stat: Skill::STAT_NAMES[3])
Skill.create(name: 'Manipulacja', start_value: 8, parent_stat: Skill::STAT_NAMES[3])
Skill.create(name: 'Obserwacja', start_value: 8, parent_stat: Skill::STAT_NAMES[3])
Skill.create(name: 'Teleoperacja', start_value: 8, parent_stat: Skill::STAT_NAMES[3])
Skill.create(name: 'Ukrycie/szukanie', start_value: 8, parent_stat: Skill::STAT_NAMES[3])
Skill.create(name: 'Ars amandi', start_value: 4, parent_stat: Skill::STAT_NAMES[3])
Skill.create(name: 'Broń pokładowa', start_value: 4, parent_stat: Skill::STAT_NAMES[3])
Skill.create(name: 'Cybertechnika', start_value: 4, parent_stat: Skill::STAT_NAMES[3])
Skill.create(name: 'Elektrotechnika', start_value: 4, parent_stat: Skill::STAT_NAMES[3])
Skill.create(name: 'Mechanika', start_value: 4, parent_stat: Skill::STAT_NAMES[3])
Skill.create(name: 'Memetyka', start_value: 4, parent_stat: Skill::STAT_NAMES[3])
Skill.create(name: 'Mikrotronika', start_value: 4, parent_stat: Skill::STAT_NAMES[3])
Skill.create(name: 'Nawigacja', start_value: 4, parent_stat: Skill::STAT_NAMES[3])
Skill.create(name: 'Paleoelektronika', start_value: 4, parent_stat: Skill::STAT_NAMES[3])
Skill.create(name: 'Paramedyk', start_value: 4, parent_stat: Skill::STAT_NAMES[3])
Skill.create(name: 'Przetrwanie w mieście', start_value: 4, parent_stat: Skill::STAT_NAMES[3])
Skill.create(name: 'Rusznikarz', start_value: 4, parent_stat: Skill::STAT_NAMES[3])
Skill.create(name: 'Saper', start_value: 4, parent_stat: Skill::STAT_NAMES[3])
Skill.create(name: 'Sobieradek', start_value: 4, parent_stat: Skill::STAT_NAMES[3])
Skill.create(name: 'Systemy zabezpieczeń', start_value: 4, parent_stat: Skill::STAT_NAMES[3])
Skill.create(name: 'Sztuka przetrwania', start_value: 4, parent_stat: Skill::STAT_NAMES[3])
Skill.create(name: 'Wizaż', start_value: 4, parent_stat: Skill::STAT_NAMES[3])
Skill.create(name: 'Znajomość dużego obszaru', start_value: 4, parent_stat: Skill::STAT_NAMES[3])
Skill.create(name: 'Znajomość miasta', start_value: 4, parent_stat: Skill::STAT_NAMES[3])
Skill.create(name: 'Znajomość niewielkiego terenu', start_value: 4, parent_stat: Skill::STAT_NAMES[3])
Skill.create(name: 'Czytanie z ust', start_value: 0, parent_stat: Skill::STAT_NAMES[3])
Skill.create(name: 'Kanalarstwo', start_value: 0, parent_stat: Skill::STAT_NAMES[3])
Skill.create(name: 'Kerning', start_value: 0, parent_stat: Skill::STAT_NAMES[3])
Skill.create(name: 'Koneksje', start_value: 0, parent_stat: Skill::STAT_NAMES[3])
Skill.create(name: 'Przetrwanie w terenie zmutowanym', start_value: 0, parent_stat: Skill::STAT_NAMES[3])

Skill.create(name: 'Broń długa', start_value: 8, parent_stat: Skill::STAT_NAMES[4])
Skill.create(name: 'Broń krótka', start_value: 8, parent_stat: Skill::STAT_NAMES[4])
Skill.create(name: 'Pierwsza pomoc', start_value: 8, parent_stat: Skill::STAT_NAMES[4])
Skill.create(name: 'Rzucanie', start_value: 8, parent_stat: Skill::STAT_NAMES[4])
Skill.create(name: 'Samochody', start_value: 8, parent_stat: Skill::STAT_NAMES[4])
Skill.create(name: 'Broń ciężka', start_value: 4, parent_stat: Skill::STAT_NAMES[4])
Skill.create(name: 'Łodzie', start_value: 4, parent_stat: Skill::STAT_NAMES[4])
Skill.create(name: 'Pojazdy naziemne', start_value: 4, parent_stat: Skill::STAT_NAMES[4])
Skill.create(name: 'Spadochroniarz', start_value: 4, parent_stat: Skill::STAT_NAMES[4])
Skill.create(name: 'Ślusarz', start_value: 4, parent_stat: Skill::STAT_NAMES[4])
Skill.create(name: 'Ziemioloty', start_value: 4, parent_stat: Skill::STAT_NAMES[4])
Skill.create(name: 'Pionowzloty', start_value: 0, parent_stat: Skill::STAT_NAMES[4])
Skill.create(name: 'Prestidigitator', start_value: 0, parent_stat: Skill::STAT_NAMES[4])
Skill.create(name: 'Samoloty', start_value: 0, parent_stat: Skill::STAT_NAMES[4])
Skill.create(name: 'Sterowce', start_value: 0, parent_stat: Skill::STAT_NAMES[4])

Skill.create(name: 'Broń drzewcowa', start_value: 8, parent_stat: Skill::STAT_NAMES[5])
Skill.create(name: 'Broń obuchowa', start_value: 8, parent_stat: Skill::STAT_NAMES[5])
Skill.create(name: 'Lekkoatletyka', start_value: 8, parent_stat: Skill::STAT_NAMES[5], is_equal_to_stat: true)
Skill.create(name: 'Miecze', start_value: 8, parent_stat: Skill::STAT_NAMES[5])
Skill.create(name: 'Motocykle', start_value: 8, parent_stat: Skill::STAT_NAMES[5])
Skill.create(name: 'Noże', start_value: 8, parent_stat: Skill::STAT_NAMES[5])
Skill.create(name: 'Pancerze wspomagane', start_value: 8, parent_stat: Skill::STAT_NAMES[5])
Skill.create(name: 'Rowery', start_value: 8, parent_stat: Skill::STAT_NAMES[5])
Skill.create(name: 'Skradanie', start_value: 8, parent_stat: Skill::STAT_NAMES[5])
Skill.create(name: 'Szermierka', start_value: 8, parent_stat: Skill::STAT_NAMES[5])
Skill.create(name: 'Walka wręcz', start_value: 8, parent_stat: Skill::STAT_NAMES[5])
Skill.create(name: 'Walka w zwarciu', start_value: 8, parent_stat: Skill::STAT_NAMES[5])
Skill.create(name: 'Wspinaczka', start_value: 8, parent_stat: Skill::STAT_NAMES[5])
Skill.create(name: 'Broń segmentowa', start_value: 4, parent_stat: Skill::STAT_NAMES[5])
Skill.create(name: 'Deski', start_value: 4, parent_stat: Skill::STAT_NAMES[5])
Skill.create(name: 'Egzoszkielety', start_value: 4, parent_stat: Skill::STAT_NAMES[5])
Skill.create(name: 'Łyżwy i rolki', start_value: 4, parent_stat: Skill::STAT_NAMES[5])
Skill.create(name: 'Szybkie wydobycie', start_value: 4, parent_stat: Skill::STAT_NAMES[5])
Skill.create(name: 'Mikrograwitacja', start_value: 0, parent_stat: Skill::STAT_NAMES[5])
Skill.create(name: 'Ucieczka', start_value: 0, parent_stat: Skill::STAT_NAMES[5])

Implication.create(name: '404', description: 'Dużo tekstu', is_advantage: false, max_level: 1, point_cost: 15)
Implication.create(name: 'Karany', description: 'Dużo tekstu', is_advantage: false, max_level: 1, point_cost: 10)
Implication.create(name: 'Martwy', description: 'Dużo tekstu', is_advantage: false, max_level: 1, point_cost: 10)
Implication.create(name: 'Kiepski wzrok', description: 'Dużo tekstu', is_advantage: false, max_level: 5, point_cost: 1)

Implication.create(name: 'Agent', description: 'Dużo tekstu', is_advantage: true, max_level: 4, point_cost: 5)
Implication.create(name: 'Alternatywna tożsamość', description: 'Dużo tekstu', is_advantage: true, max_level: 1,
                   point_cost: 15)
Implication.create(name: 'Dodatkowa tożsamość', description: 'Dużo tekstu', is_advantage: true, max_level: 1,
                   point_cost: 5)
